<a href="https://colab.research.google.com/github/mattpolands/Adding-Google-Colab-project/blob/main/PyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pytorch as a tensor array library
#a tensor can be thought of as a generalized matrix
#you can have n-D tensors
#scalar - single number or value
#vector - 1D array - also could be called 1D tensor
#matrix - 2D array - also could be called 2D tensor
#tensor - 3D or higher array
#we use tensors because it is an easy way to arrange data

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
torch.__version__

'1.13.1+cu116'

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
x = torch.from_numpy(arr)

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
type(x)

torch.Tensor

In [ ]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [ ]:
x.dtype

torch.int64

In [ ]:
arr2d = np.arange(0.0,12.0)

In [ ]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
arr2d = arr2d.reshape(4,3)

In [ ]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr2d)

In [ ]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [ ]:
#using method from_numpy creates a direct link between the created array and the tensor
arr

array([1, 2, 3, 4, 5])

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
arr[1] = 98

In [ ]:
arr

array([ 1, 98,  3,  4,  5])

In [ ]:
x

tensor([ 1, 98,  3,  4,  5])

In [ ]:
#how to avoid this 
my_arr = np.arange(0.0,10.0)

In [ ]:
my_tensor = torch.tensor(my_arr)

In [ ]:
my_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [ ]:
my_other_tensor = torch.from_numpy(my_arr)

In [ ]:
my_other_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [ ]:
#when we use method .tensor we create a copy
my_arr[0] = 999 

In [ ]:
my_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [ ]:
my_other_tensor

tensor([999.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       dtype=torch.float64)

In [ ]:
#above can see how changing the index in my_arr didn't change my_tensor but did change my_other_tensor

In [ ]:
new_arr = np.array([1,2,3])

In [ ]:
new_arr.dtype

dtype('int64')

In [ ]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [ ]:
#tricksy naming Tensor method (tensor with a capital 'T') short hand to create a floating point tensor
#short hand for method FloatTensor
my_tensor = torch.Tensor(new_arr)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
#often we will want to make an "initializer" tensor
#essentially an empty or predetermined tensor that is ready to receive inputs
#we want to retain a block of memory
torch.empty(2,2)

tensor([[ 4.9514e-34,  0.0000e+00],
        [-4.6655e+00,  4.5619e-41]])

In [ ]:
#the above numbers are either 0 or very close to 0
#reports like this because challenging for computers have limits on storing floating numbers accuracy


In [ ]:
#if you need a tensor of absolute/actual zeros
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#can also change this to integers
#usually avoid this because more processing and in turn bogs down training time
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones(5,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
#very similar to numpy naming
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [ ]:
my_tensor = torch.Tensor([1,2,3])

In [ ]:
my_tensor

tensor([1., 2., 3.])

In [ ]:
#change the dtype
my_tensor.type(torch.float)

tensor([1., 2., 3.])

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
#normal uniform random distribution
#returns random samples from a uniform distribution from 0 to 1
#all these samples have an equal likelihood of being picked
torch.rand(4,3)

tensor([[0.9757, 0.3800, 0.6995],
        [0.3239, 0.4843, 0.2986],
        [0.6955, 0.3600, 0.5854],
        [0.5949, 0.8424, 0.5706]])

In [ ]:
#normal standard distribution
#mean at 0 and a standard deviation (or sigma) of 1
torch.randn(4,3)

tensor([[ 1.0862,  0.9137, -0.9638],
        [-0.5819, -0.6892,  0.8733],
        [-1.6461, -1.9152, -0.1646],
        [ 0.4728, -1.1450,  0.6318]])

In [ ]:
#randint returns randome integers from low exclusivity to high exclusivity
torch.randint(low=0, high=120, size=(4,3))

tensor([[ 85,   3,  55],
        [  8,  80,  22],
        [ 91,  32, 101],
        [ 81,  42,  12]])

In [ ]:
x = torch.zeros(2,5)

In [ ]:
torch.rand_like(x)

tensor([[0.4081, 0.5628, 0.2672, 0.0374, 0.4897],
        [0.1918, 0.4313, 0.5043, 0.9739, 0.3478]])

In [ ]:
#above takes in x shaped tensor and applies the rand method

In [ ]:
torch.randn_like(x)

tensor([[ 0.6815, -0.7524,  1.2531, -0.3196, -0.6083],
        [ 1.2509,  0.5616, -0.8708, -0.5268,  0.3319]])

In [ ]:
torch.randint_like(x,low=0,high=5)

tensor([[4., 0., 2., 0., 2.],
        [0., 0., 0., 4., 2.]])

In [ ]:
#to keep same random set of numbers ie. seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.arange(6).reshape(2,3)

In [ ]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x[1,1]

tensor(4)

In [ ]:
x[:1]

tensor([[0, 1, 2]])

In [ ]:
x[:,1]

tensor([1, 4])

In [ ]:
x[:,1:]

tensor([[1, 2],
        [4, 5]])

In [ ]:
x = torch.arange(10)

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#view and reshape methods are very similar
#both only change x temporarily
#have to rename to make change permanent

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
z = x.view(2,5)

In [ ]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#here comes the difference between view and reshape
#view allows you to link variables
#example if I change x it will change z
x[1] = 30

In [ ]:
x

tensor([ 0, 30,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
z

tensor([[ 0, 30,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [ ]:
x= torch.arange(10)

In [ ]:
#Pytorch has the ability to infer what the 2nd dimension might be
#this request is delineated by '-1'
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#has limits, if it isn't possible than it will report an error
y = torch.arange(11)

In [ ]:
y.view(2,-1)

RuntimeError: ignored

In [ ]:
a = torch.Tensor([1,2,3])

In [ ]:
b = torch.Tensor([5,6,7])

In [ ]:
a + b

tensor([ 6.,  8., 10.])

In [ ]:
a - b

tensor([-4., -4., -4.])

In [ ]:
torch.add(a,b)

tensor([ 6.,  8., 10.])

In [ ]:
a.mul(b)

tensor([ 5., 12., 21.])

In [ ]:
#want to change assignment of a, choose arithmetic desired followed by the _
a.mul_(b)

tensor([ 5., 12., 21.])

In [ ]:
a

tensor([ 5., 12., 21.])

In [ ]:
a = torch.Tensor([1,2,3])

In [ ]:
#want matrix multiplication need to use dot method
a.dot(b)

tensor(38.)

In [ ]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [ ]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [ ]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
#matrix multiplication
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [ ]:
#another way is with @
a@b

tensor([[56, 62],
        [80, 89]])

In [ ]:
#Euclidean norm or L2
x = torch.Tensor([2,3,4,5])

In [ ]:
#returns back the Euclidean norm
x.norm()

tensor(7.3485)

In [ ]:
#return back the number of elements
x.numel()

4

In [ ]:
#or
len(x)

4

In [ ]:
#not affective in multiple dimensions
#only returns back the number of rows
len(a)

2

In [ ]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
a.numel()

6